"""Add stats streak fields

Revision ID: 203fdfb0872d
Revises: 
Create Date: 2026-05-11 17:22:40.615627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203fdfb0872d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('best_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_column('best_streak')
        batch_op.drop_column('current_streak')

    # ### end Alembic commands ###
